### ISSUE TITLE
Variable is not prefixed with `$inuit-`

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/settings.responsive#3]
`$breakpoint` variable is not prefixed with `$inuit-`. Is it by any chance intentional?

**Comment by csshugs** [comment]
Just a ping on this.

**Comment by nenadjelovac** [comment]
@csshugs thx! I was about to ping the other day but got distracted and forgot :)

**Comment by csshugs** [comment]
Never put off till tomorrow what you can do today ;-)

**Comment by florianbouvot** [comment]
ping

**Comment by csshugs** [comment]
> Is it by any chance intentional?

I assume that this is not intentional. But since `$breakpoint` is referenced in other modules, I think we would have too much work to do to fix it. Consequently, I think we should just leave it be (and hope the best) and reopen this issue, if this pops up as a real problem, i.e. conflicting Sass variables.

Don't forget, it's all just pre-alpha.

@inuitcss/core Close this?

**Comment by florianbouvot** [comment]
@csshugs you're right, I think we can close this for now.

**Comment by nenadjelovac** [comment]
@csshugs it's safe to close now as we're doing it differently in new version of inuitcss.
