### ISSUE TITLE
Why using px instead of em?

### ISSUE THREAD

**Issue by minimaldesign** [inuitcss/settings.responsive#4]
Not really an issue, but I'm thinking other people might be wondering the same thing…

I'm sure you're aware of the differences between breakpoints in `em` vs `px` so I was wondering why you're opting for pixels… Thanks!

Here's [some context][1] if anyone's wondering what I'm talking about.

[1]:http://stackoverflow.com/questions/22228568/switching-to-em-based-media-queries

**Comment by anselmh** [comment]
Actually I do agree here, I’m used to use `rem`/`em` values for everything nowadays so in my opinion it makes sense to write media queries the same way.

But actually `px` values are not only used here but on the entire project for spacings etc. so it would be more of a meta bug affecting the whole framework.

@csswizardry may I ask if there is any specific reason why you want to keep using `px` or is it just because of prior versions using `px`, too?

**Comment by minimaldesign** [comment]
Personally, I've just switched to an em based approach and I'm also not crazy about the naming, so that's what I got:

    "sm"        "screen and (min-width: 30em)",
    "md"        "screen and (min-width: 48em)",
    "lg"        "screen and (min-width: 62em)",
    "xl"        "screen and (min-width: 80em)",

**Comment by csswizardry** [comment]
These really are only defaults, so they could be changed to ems, rems, cm, anything one wishes.

However, perhaps it’s more responsible of me to use ems as defaults…?

**Comment by minimaldesign** [comment]
It probably is… Check out the link in my original question for more info. I only asked because you're a CSS guru and I thought you probably knew something I didn't :)

**Comment by florianbouvot** [comment]
:+1: for ems as defaults for responsive settings
